package com.nacei.component;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class BindElementJPanel {
    private JTextField element_sgin;
    private JTextField cell_content_text;
    private JPanel bindJPane;
    private JComboBox option_comboBox;
    private JSpinner spinner_delayed;
    private JTextField element_type;

    public JTextField getElement_sgin() {
        return element_sgin;
    }

    public void setElement_sgin(JTextField element_sgin) {
        this.element_sgin = element_sgin;
    }

    public JTextField getCell_content_text() {
        return cell_content_text;
    }

    public void setCell_content_text(JTextField cell_content_text) {
        this.cell_content_text = cell_content_text;
    }


    public JPanel getBindJPane() {
        return bindJPane;
    }

    public void setBindJPane(JPanel bindJPane) {
        this.bindJPane = bindJPane;
    }

    public JComboBox getOption_comboBox() {
        return option_comboBox;
    }

    public void setOption_comboBox(JComboBox option_comboBox) {
        this.option_comboBox = option_comboBox;
    }

    public JSpinner getSpinner_delayed() {
        return spinner_delayed;
    }

    public void setSpinner_delayed(JSpinner spinner_delayed) {
        this.spinner_delayed = spinner_delayed;
    }

    public JTextField getElement_type() {
        return element_type;
    }

    public void setElement_type(JTextField element_type) {
        this.element_type = element_type;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        bindJPane = new JPanel();
        bindJPane.setLayout(new GridLayoutManager(1, 5, new Insets(5, 5, 5, 5), -1, -1));
        bindJPane.setBackground(new Color(-1));
        element_sgin = new JTextField();
        element_sgin.setEditable(false);
        element_sgin.setEnabled(true);
        element_sgin.setMargin(new Insets(2, 6, 2, 6));
        element_sgin.setText("");
        bindJPane.add(element_sgin, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, -1), null, 0, false));
        element_type = new JTextField();
        element_type.setEditable(false);
        element_type.setText("");
        bindJPane.add(element_type, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, -1), null, 0, false));
        option_comboBox = new JComboBox();
        bindJPane.add(option_comboBox, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(30, -1), null, 0, false));
        spinner_delayed = new JSpinner();
        bindJPane.add(spinner_delayed, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(20, -1), null, 0, false));
        cell_content_text = new JTextField();
        cell_content_text.setMargin(new Insets(2, 6, 2, 6));
        bindJPane.add(cell_content_text, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(250, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return bindJPane;
    }
}
